Adds packet capture
Rans4ckeR/RS.Fritz.Manager pull request #17
Opened 2022-03-17 23:56 UTC by RoSchmi

2022-03-18 18:54 UTC, Rans4ckeR requested changes

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.API/Capture/CaptureControlService.cs
> +        var file = new FileInfo(FormattableString.Invariant($"{folderPath}\\{filePrefix}_{DateTime.Now.ToString("dd/MM/yyyy'_'HH'_'mm'.'ss", CultureInfo.CreateSpecificCulture("de"))}.eth"));
I suggest to use [ISO8601](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Sortable) format here using:

```C#
DateTime.Now.ToString("s").Replace(":", string.Empty)
```

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.API/Capture/CaptureControlService.cs
> +        using Stream? downloadStream = await response.Content.ReadAsStreamAsync();
you can use ```await using``` here

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.API/Extensions/ServiceCollectionExtensions.cs
> +            .AddSingleton<IClientFactory<ICaptureControlService>, ClientFactory<ICaptureControlService>>();
can be removed

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.UI/RS - Backup.Fritz.Manager.UI.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
can be removed

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.UI/UserControls/Capture/CaptureControlCaptureViewModel.cs
> +    private const string Host = "fritz.box";
This does not work on my network because I don't use the FritzBox as DNS server. Better to use the actual IPv6 or IPv4 address.

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.UI/UserControls/Capture/CaptureControlCaptureViewModel.cs
> +    protected override async Task DoExecuteDefaultCommandAsync(CancellationToken cancellationToken = default)
You can use this syntax:

```C#
protected override Task DoExecuteDefaultCommandAsync(CancellationToken cancellationToken = default)
{
    return Task.CompletedTask;
}
```

2022-03-18 18:54 UTC, Rans4ckeR commented on RS.Fritz.Manager.API/Utils/SpecialFolder.cs
> +﻿namespace RS.Fritz.Manager.API
Can you move this to the UI project? The API is cross platform, while the UI is Windows only.

2022-03-19 16:46 UTC, RoSchmi commented
I made the requested changes except some minor things where I was not sure how to do it. Can you please change these?

2022-03-19 16:57 UTC, RoSchmi commented on RS.Fritz.Manager.UI/RS - Backup.Fritz.Manager.UI.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Can you please do this?

2022-03-19 19:24 UTC, merged

2022-03-19 19:28 UTC, Rans4ckeR commented
@RoSchmi thanks, nice addition